//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     luoyikun 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/login.proto
// Note: requires additional types generated from: second.proto
namespace network
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cs_login")]
  public partial class cs_login : CSPacketBase
  {
    public cs_login() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _add;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"add", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string add
    {
      get { return _add; }
      set { _add = value; }
    }
    private network.cs_second _second;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"second", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public network.cs_second second
    {
      get { return _second; }
      set { _second = value; }
    } 
	public override void Clear()
	{   
	  //TODO 返回引用池中需要把成员变量设置为默认值
	}
	public override Id 
	{ 
		get {return (int)Network.NetMsgID.cs_login} 
	} 
     	
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sc_login")]
  public partial class sc_login : SCPacketBase
  {
    public sc_login() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    } 
	public override void Clear()
	{   
	  //TODO 返回引用池中需要把成员变量设置为默认值
	}
	public override Id 
	{ 
		get {return (int)Network.NetMsgID.sc_login} 
	} 
     	
  }
  
}